name: Portable-Portals
description: Fast Easy Portable Portals
main: me.sniperzciinema.portal.PortablePortals
version: 0.4
author: SniperzCiinema

commands:
   pportals:
      description: Spawn a portal
      usage: /<command>
      aliases: [p, portableportals, portal, pportal]
   preload:
      description: Reload files
      usage: /<command>
      aliases: [pr, portableportalsreload, portalreload, pportalreload]

permissions:
   PortablePortals.*:
      default: op
      children:
         PortablePortals.Use: true
         PortablePortals.Spawn: true
   PortablePortals.Use:
      default: true
   PortablePortals.Create:
      default: true